# Contribuire {#sec-contributing}

Questo libro è stato sviluppato in maniera aperta, e non sarebbe così buono senza i vostri contributi.
Ci sono diversi modi in cui potete aiutare a rendere il libro ancora migliore:

-   Se non capite qualcosa, per favore [fatemelo sapere](mailto:h.wickham@gmail.com).
    Il vostro feedback su ciò che è confuso o difficile da capire è prezioso.

-   Se notate un errore di battitura, sentitevi liberi di modificare la pagina sottostante e inviare una pull request.
    Se non l'avete mai fatto prima, il processo è molto semplice:

    -   Cliccate su "edit this page" nella barra laterale.

    -   Fate le modifiche usando l'editor in-page di GitHub e salvate.

    -   Inviate una pull request e includete una breve descrizione delle vostre modifiche.
        "Fixing typos" è perfettamente adeguato.

    -   Se fate modifiche significative, includete la frase "I assign the copyright of this contribution to Hadley Wickham" - ho bisogno di questo per poter pubblicare il libro stampato.