# Benvenuto {.unnumbered}

Questo è il sito web della seconda edizione di **"R for Data Science"**.
Questo libro ti insegnerà come fare data science con R: imparerai come inserire i tuoi dati in R, come strutturarli nel modo più utile, trasformarli e visualizzarli.

In questo libro troverai un percorso pratico di competenze per la data science.
Proprio come un chimico impara a pulire le provette e organizzare un laboratorio, tu imparerai a pulire i dati e creare grafici---e molte altre cose oltre a queste.
Queste sono le competenze che permettono alla data science di funzionare, e qui troverai le migliori pratiche per fare ciascuna di queste cose con R.
Imparerai come usare la grammar of graphics, la programmazione letterata e la ricerca riproducibile per risparmiare tempo.
Imparerai anche come gestire le risorse cognitive per facilitare le scoperte durante il wrangling, la visualizzazione e l'esplorazione dei dati.

Questo sito web è e sarà sempre gratuito, sotto licenza [CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/us/).
Se desideri una copia fisica del libro, puoi ordinarla su [Amazon](https://www.amazon.com/dp/1492097403?&tag=hadlwick-20).
Se apprezzi leggere il libro gratuitamente e vorresti ricambiare, per favore fai una donazione a [Kākāpō Recovery](https://www.doc.govt.nz/kakapo-donate): il [kākāpō](https://www.youtube.com/watch?v=9T1vfsHYiKY) (che appare sulla copertina di R4DS) è un pappagallo gravemente minacciato di estinzione originario della Nuova Zelanda; ne sono rimasti solo 244.

Se parli un'altra lingua, potresti essere interessato alle traduzioni disponibili gratuitamente della prima edizione:

-   [Spagnolo](http://es.r4ds.hadley.nz)
-   [Turco](https://tr.r4ds.hadley.nz)
-   [Portoghese](https://pt.r4ds.hadley.nz)

Puoi trovare le soluzioni suggerite agli esercizi del libro su <https://mine-cetinkaya-rundel.github.io/r4ds-solutions>.

Si prega di notare che R4DS utilizza un [Codice di Condotta per Contributori](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html).
Contribuendo a questo libro, accetti di rispettarne i termini.
