# Prefazione alla seconda edizione {.unnumbered}

Benvenuti alla seconda edizione di "R for Data Science"!
Questa è una rielaborazione importante della prima edizione, che rimuove materiale che non riteniamo più utile, aggiunge materiale che avremmo voluto includere nella prima edizione e aggiorna in generale il testo e il codice per riflettere i cambiamenti nelle migliori pratiche.
Siamo anche molto entusiasti di dare il benvenuto a una nuova co-autrice: Mine Çetinkaya-Rundel, una nota educatrice di data science e una delle nostre colleghe in Posit (l'azienda precedentemente nota come RStudio).

Segue un breve riassunto dei cambiamenti più importanti:

-   La prima parte del libro è stata rinominata "Gioco Completo".
    L'obiettivo di questa sezione è dare i dettagli generali del "gioco completo" della data science prima di immergerci nei dettagli.

-   La seconda parte del libro è "Visualizzare".
    Questa parte fornisce una copertura più approfondita degli strumenti di visualizzazione dei dati e delle migliori pratiche rispetto alla prima edizione.
    Il posto migliore per ottenere tutti i dettagli rimane il [libro su ggplot2](http://ggplot2-book.org/), ma ora R4DS copre più delle tecniche più importanti.

-   La terza parte del libro si chiama ora "Transformazione" e guadagna nuovi capitoli sui numeri, vettori logici e valori mancanti.
    Questi erano precedentemente parti del capitolo sulla trasformazione dei dati, ma avevano bisogno di molto più spazio per coprire tutti i dettagli.

-   La quarta parte del libro si chiama "Importazione".
    È un nuovo insieme di capitoli che va oltre la lettura di file di testo semplici per lavorare con fogli di calcolo, estrarre dati da database, lavorare con big data, strutturare dati gerarchici e fare scraping di dati da siti web.

-   La parte "Programmare" rimane, ma è stata riscritta dall'inizio per concentrarsi sulle parti più importanti della scrittura di funzioni e dell'iterazione.
    La scrittura di funzioni ora include dettagli su come incapsulare le funzioni del tidyverse (gestendo le sfide della tidy evaluation), dal momento che questo è diventato molto più facile e importante negli ultimi anni.
    Abbiamo aggiunto un nuovo capitolo sulle funzioni importanti di R base che probabilmente vedrai nel codice R trovato "in natura".

-   La parte sulla modellazione è stata rimossa.
    Non abbiamo mai avuto abbastanza spazio per rendere giustizia alla modellazione, e ora ci sono risorse molto migliori disponibili.
    Generalmente raccomandiamo di usare i pacchetti [tidymodels](https://www.tidymodels.org/) e di leggere [Tidy Modeling with R](https://www.tmwr.org/) di Max Kuhn e Julia Silge.

-   La parte "Comunicare" rimane, ma è stata completamente aggiornata per presentare [Quarto](https://quarto.org/) invece di R Markdown.
    Questa edizione del libro è stata scritta in Quarto, ed è chiaramente lo strumento del futuro.

## Nota sulla traduzione italiana {.unnumbered}

**Ultimo Aggiornamento** `r format(Sys.time(), '%d %B, %Y')`

La traduzione italiana del libro R4DS è stata condotta da [Luca Vedovelli](https://lucavd.netlify.app/) su [esplicita autorizzazione]{.underline} dell'autore (Hadley Wickam) e dell'editore O'Reilly che detiene i diritti di traduzione.

Il motivo che mi ha spinto alla traduzione di un testo fondamentale per chi si avvicina all'ambiente di R e della *data science* è la volontà di abbattere almeno uno scoglio (la lingua) lungo il loro apprendimento, per permettere al lettore (che io immagino essere una mia studentessa o studente) di concentrarsi sui concetti e tecniche.

Ho cercato di cambiare il minimo possibile dal libro originale mantenendo i termini inglesi dove i corrispondenti italiani suonavano desueti o ridicoli.
Anche link, autori, ringraziamenti sono rimasti inalterati.
Anche il codice è rimasto inalterato (ho tradotto solo le note di testo interne al codice).

La traduzione è stata effettuata sulla **seconda edizione** (aggiornata a Giugno 2025).

Potete segnalare errori o suggerimenti (molto apprezzati!) aprendo una issue o un pull request alla [repository GitHub](https://https://github.com/lucavd/r4ds_ita_2nd_ed) della traduzione.
